# Generated by Django 5.2.6 on 2025-10-19 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('publish_date', models.DateTimeField()),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('requires_registration', models.BooleanField(default=False)),
                ('max_attendees', models.IntegerField(blank=True, null=True)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('worship', 'Worship Service'), ('conference', 'Conference'), ('seminar', 'Seminar'), ('fellowship', 'Fellowship'), ('outreach', 'Outreach'), ('youth', 'Youth Event'), ('other', 'Other')], default='other', max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Giving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('giving_type', models.CharField(choices=[('tithe', 'Tithe'), ('offering', 'Offering'), ('special', 'Special Offering'), ('pledge', 'Pledge'), ('mission', 'Mission'), ('building', 'Building Fund'), ('other', 'Other')], max_length=50)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('card', 'Card')], max_length=50)),
                ('transaction_ref', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_answered', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('health', 'Health'), ('family', 'Family'), ('finance', 'Finance'), ('spiritual', 'Spiritual'), ('other', 'Other')], default='other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Testimonies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('attended', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='church.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registered_at'],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PrayerSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prayer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporters', to='church.prayerrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('prayer_request', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Sermon title', max_length=255)),
                ('preacher', models.CharField(db_column='pastor', help_text='Pastor/Preacher name', max_length=200)),
                ('description', models.TextField(help_text='Sermon description')),
                ('scripture_reference', models.CharField(blank=True, max_length=100)),
                ('topics', models.CharField(blank=True, default='', help_text='Comma-separated topics (e.g., Faith, Prayer, Healing)', max_length=500)),
                ('duration', models.CharField(blank=True, help_text='Duration in MM:SS format (e.g., 45:30)', max_length=10, null=True)),
                ('audio_file', models.FileField(blank=True, help_text='Audio file (MP3, WAV, M4A, etc.)', max_length=500, null=True, upload_to='sermons/audio/%Y/%m/')),
                ('video_file', models.FileField(blank=True, help_text='Video file (MP4, MOV, AVI, etc.)', max_length=500, null=True, upload_to='sermons/video/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Sermon thumbnail image (JPG, PNG, etc.)', max_length=500, null=True, upload_to='sermons/thumbnails/%Y/%m/')),
                ('sermon_date', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0, help_text='Number of views')),
                ('category', models.CharField(choices=[('Sunday Service', 'Sunday Service'), ('Midweek Service', 'Midweek Service'), ('Youth Service', 'Youth Service'), ('Special Event', 'Special Event'), ('Conference', 'Conference'), ('Revival', 'Revival'), ('Worship Night', 'Worship Night'), ('Bible Study', 'Bible Study')], default='Sunday Service', help_text='Sermon category', max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='Is sermon active/visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this sermon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_sermons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sermon',
                'verbose_name_plural': 'Sermons',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='church_serm_created_135142_idx'), models.Index(fields=['category'], name='church_serm_categor_bb7229_idx'), models.Index(fields=['preacher'], name='church_serm_pastor_b1e2b4_idx')],
            },
        ),
    ]
