# Generated by Django 5.2.6 on 2025-10-26 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_prayerrequest_priority_prayercomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='category',
            field=models.CharField(choices=[('healing', 'Healing'), ('financial', 'Financial Breakthrough'), ('family', 'Family Restoration'), ('salvation', 'Salvation'), ('deliverance', 'Deliverance'), ('career', 'Career/Job'), ('answered_prayer', 'Answered Prayer'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='testimony',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='testimonies/photos/'),
        ),
        migrations.AddField(
            model_name='testimony',
            name='prayer_request',
            field=models.ForeignKey(blank=True, help_text='Link testimony to a prayer request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonies', to='church.prayerrequest'),
        ),
        migrations.AddField(
            model_name='testimony',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='testimonies/videos/'),
        ),
    ]
