# Generated by Django 5.2.6 on 2025-10-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_add_testimony_media_and_prayer_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='testimony_type',
            field=models.CharField(choices=[('regular', 'Regular Testimony'), ('sunday_service', 'Sunday Service Testimony')], default='regular', help_text='Type of testimony - regular or Sunday service', max_length=20),
        ),
        migrations.AddField(
            model_name='testimony',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Thumbnail for Sunday Service testimonies', null=True, upload_to='testimonies/thumbnails/'),
        ),
    ]
