# Generated by Django 5.2.6 on 2025-10-26 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_add_sunday_service_testimony'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonyPraise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('testimony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='praises', to='church.testimony')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimony_praises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Testimony Praises',
                'ordering': ['-created_at'],
                'unique_together': {('testimony', 'user')},
            },
        ),
    ]
