# Generated by Django 5.2.6 on 2025-10-28 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_add_testimony_praise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giving',
            options={'ordering': ['-created_at'], 'verbose_name': 'Giving', 'verbose_name_plural': 'Givings'},
        ),
        migrations.AddField(
            model_name='giving',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giving',
            name='confirmation_code',
            field=models.CharField(blank=True, help_text='Payment confirmation code from payment provider', max_length=100),
        ),
        migrations.AddField(
            model_name='giving',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='giving',
            name='donor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='giving',
            name='donor_name',
            field=models.CharField(blank=True, help_text='Name of donor (for anonymous or guest donations)', max_length=200),
        ),
        migrations.AddField(
            model_name='giving',
            name='donor_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='giving',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='giving',
            name='merchant_reference',
            field=models.CharField(blank=True, help_text='Internal merchant reference for the transaction', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='giving',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='giving',
            name='pesapal_tracking_id',
            field=models.CharField(blank=True, help_text='Pesapal order tracking ID', max_length=100),
        ),
        migrations.AddField(
            model_name='giving',
            name='recurring_frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20),
        ),
        migrations.AddField(
            model_name='giving',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='giving',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes from donor'),
        ),
        migrations.AlterField(
            model_name='giving',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('mtn_money', 'MTN Mobile Money'), ('tigo_pesa', 'Tigo Pesa'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='giving',
            name='transaction_ref',
            field=models.CharField(blank=True, help_text='Payment gateway transaction reference', max_length=100),
        ),
        migrations.AlterField(
            model_name='giving',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who made the donation (null for anonymous)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=200, unique=True)),
                ('order_tracking_id', models.CharField(blank=True, max_length=200)),
                ('merchant_reference', models.CharField(max_length=200)),
                ('gateway', models.CharField(choices=[('pesapal', 'Pesapal'), ('mpesa', 'M-Pesa STK Push'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('manual', 'Manual Entry')], default='pesapal', max_length=50)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='initiated', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_account', models.CharField(blank=True, help_text='Phone number or card last 4 digits', max_length=100)),
                ('confirmation_code', models.CharField(blank=True, max_length=200)),
                ('payment_status_description', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('request_data', models.JSONField(blank=True, help_text='Request payload sent to payment gateway', null=True)),
                ('response_data', models.JSONField(blank=True, help_text='Response from payment gateway', null=True)),
                ('callback_data', models.JSONField(blank=True, help_text='Callback/IPN data received', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('giving', models.ForeignKey(help_text='Related giving record', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='church.giving')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_id'], name='church_paym_transac_732a52_idx'), models.Index(fields=['order_tracking_id'], name='church_paym_order_t_1b25a4_idx'), models.Index(fields=['merchant_reference'], name='church_paym_merchan_1d2979_idx'), models.Index(fields=['status'], name='church_paym_status_6ff4af_idx')],
            },
        ),
    ]
