# Generated by Django 5.2.6 on 2025-11-12 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_enhanced_payment_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Live stream title', max_length=255)),
                ('youtube_url', models.URLField(help_text='YouTube live stream URL')),
                ('youtube_video_id', models.CharField(help_text='YouTube video ID', max_length=100)),
                ('description', models.TextField(help_text='Stream description')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Stream thumbnail URL', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended')], default='scheduled', help_text='Stream status', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='When the stream is scheduled', null=True)),
                ('viewer_count', models.IntegerField(default=0, help_text='Current viewer count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this stream', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_streams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Stream',
                'verbose_name_plural': 'Live Streams',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='church_live_created_17c53b_idx'), models.Index(fields=['status'], name='church_live_status_e43221_idx'), models.Index(fields=['scheduled_for'], name='church_live_schedul_cb988c_idx')],
            },
        ),
    ]
