# Generated by Django 5.2.6 on 2025-11-16 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0007_livestream'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(help_text='Name to display (stored for deleted users)', max_length=100)),
                ('message', models.TextField(help_text='Chat message content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('live_stream', models.ForeignKey(help_text='Associated live stream', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='church.livestream')),
                ('user', models.ForeignKey(help_text='User who sent the message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Chat Message',
                'verbose_name_plural': 'Live Chat Messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['live_stream', 'created_at'], name='church_live_live_st_038e66_idx')],
            },
        ),
    ]
