# Generated by Django 5.2.6 on 2025-10-11 10:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('chief_apostle', 'Chief Apostle'), ('katibu_kiongozi', 'Katibu Kiongozi'), ('apostle', 'Apostle'), ('senior_pastor', 'Senior Pastor'), ('bishop', 'Bishop'), ('editor', 'Editor'), ('data_entry', 'Data Entry'), ('member', 'Member')], default='member', help_text='User role in the church system', max_length=20)),
                ('church_position', models.CharField(blank=True, choices=[('mtume_mkuu', 'Mtume Mkuu'), ('msaidizi_binafsi_mtume', 'Msaidizi Binafsi wa Mtume Mkuu'), ('mtume', 'Mtume'), ('mchungaji_kiongozi', 'Mchungaji Kiongozi'), ('mchungaji', 'Mchungaji'), ('katibu', 'Katibu'), ('mtawala', 'Mtawala'), ('askofu', 'Askofu'), ('cell_leader', 'Cell Leader'), ('mweka_hazina', 'Mweka Hazina'), ('mwanakamati', 'Mwanakamati'), ('mjumbe_board', 'Mjumbe wa Board'), ('funguka', 'Funguka'), ('ict', 'ICT'), ('tv', 'TV'), ('sunday_school_teacher', 'Sunday School Teacher'), ('walinzi', 'Walinzi'), ('muumini', 'Muumini')], help_text='Position in church', max_length=30, null=True)),
                ('membership_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('registration_number', models.CharField(blank=True, help_text='Church registration number', max_length=50, null=True)),
                ('membership_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('visitor', 'Visitor')], default='visitor', max_length=20)),
                ('country', models.CharField(blank=True, choices=[('tanzania', 'Tanzania'), ('kenya', 'Kenya'), ('malawi', 'Malawi'), ('zambia', 'Zambia'), ('rwanda', 'Rwanda'), ('burundi', 'Burundi'), ('congo', 'Republic of Congo'), ('mozambique', 'Mozambique'), ('botswana', 'Botswana'), ('south_africa', 'South Africa'), ('south_sudan', 'South Sudan'), ('uk', 'UK'), ('usa', 'USA'), ('pakistan', 'Pakistan'), ('india', 'India')], max_length=20, null=True)),
                ('region', models.CharField(blank=True, help_text='Region/State', max_length=100, null=True)),
                ('service_region', models.CharField(blank=True, help_text='Service region (Mikoa)', max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('receive_notifications', models.BooleanField(default=True)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('sw', 'Swahili')], default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salvation_date', models.DateField(blank=True, null=True)),
                ('baptism_date', models.DateField(blank=True, null=True)),
                ('ministry', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('purpose', models.CharField(choices=[('login', 'Login Verification'), ('registration', 'Registration Verification'), ('password_reset', 'Password Reset')], default='login', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'code', 'is_used'], name='users_verif_email_c2d29b_idx'), models.Index(fields=['expires_at'], name='users_verif_expires_4b338e_idx')],
            },
        ),
    ]
