# Generated by Django 5.2.6 on 2025-10-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_church_position_alter_user_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_number',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, help_text='Male, Female, Other', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='house_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, help_text='Single, Married, Divorced, Widowed', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='residence',
            field=models.CharField(blank=True, help_text='Residence area', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, help_text='District/City', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='membership_number',
            field=models.CharField(blank=True, help_text='Church membership number', max_length=50, null=True),
        ),
    ]
