# Generated by Django 5.2.6 on 2025-10-12 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_registration_number_user_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='membership_status',
        ),
    ]
